# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
java = '21'
spring-boot = '3.5.5'
spring-cloud = '2025.0.0'
spring-cloud-alibaba = '2023.0.3.3'
hutool = '5.8.40'
lombok = '1.18.40'
dubbo = '3.3.5'
redisson = '3.35.0'
mybatis-plus = '3.5.8'
mybatis-plus-join = '1.5.4'
guava = '33.3.1-jre'
jwt = '0.13.0'
knife4j-openapi3 = '4.5.0'
skywalking-agent = '9.5.0'
mapstruct = '1.6.3'

[libraries]
lombok = { module = 'org.projectlombok:lombok', version.ref = 'lombok' }
dubbo-bom = { module = 'org.apache.dubbo:dubbo-bom', version.ref = 'dubbo' }
hutool-bom = { module = 'cn.hutool:hutool-bom', version.ref = 'hutool' }
spring-cloud-dependencies = { module = 'org.springframework.cloud:spring-cloud-dependencies', version.ref = 'spring-cloud' }
spring-cloud-alibaba-dependencies = { module = 'com.alibaba.cloud:spring-cloud-alibaba-dependencies', version.ref = 'spring-cloud-alibaba' }
redisson-spring-boot-starter = { module = 'org.redisson:redisson-spring-boot-starter', version.ref = 'redisson' }
mybatis-plus-boot3-starter = { module = 'com.baomidou:mybatis-plus-spring-boot3-starter', version.ref = 'mybatis-plus' }
mybatis-plus-generator = { module = 'com.baomidou:mybatis-plus-generator', version.ref = 'mybatis-plus' }
mybatis-plus-join-boot-starter = { module = 'com.github.yulichang:mybatis-plus-join-boot-starter', version.ref = 'mybatis-plus-join' }
google-guava = { module = 'com.google.guava:guava', version.ref = 'guava' }
jsonwebtoken-jjwt = { module = 'io.jsonwebtoken:jjwt', version.ref = 'jwt' }
knife4j-openapi3-jakarta-spring-boot-starter = { module = 'com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter', version.ref = 'knife4j-openapi3' }
skywalking-apm-toolkit-logback = { module = 'org.apache.skywalking:apm-toolkit-logback-1.x', version.ref ='skywalking-agent' }
mapstruct = { module = 'org.mapstruct:mapstruct', version.ref ='mapstruct' }
mapstruct-processor = { module = 'org.mapstruct:mapstruct-processor', version.ref ='mapstruct' }

[plugins]
spring-boot = { id = 'org.springframework.boot', version.ref = 'spring-boot' }